# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_h28KwyG7PGh9zI4MA5cw3PpAIjuAPp
"""

print("Guggilam Chinmayi Naga Sai Lakshmi")

#Calculator
import ipywidgets as widgets
from IPython.display import display

# Define calculation functions
def add_numbers(a, b):
    return a + b

def subtract_numbers(a, b):
    return a - b

def multiply_numbers(a, b):
    return a * b

def divide_numbers(a, b):
    if b == 0:
        return "Cannot divide by zero!"
    return a / b

# Create widgets
num1 = widgets.FloatText(description='Number 1:')
num2 = widgets.FloatText(description='Number 2:')
add_button = widgets.Button(description="Add")
subtract_button = widgets.Button(description="Subtract")
multiply_button = widgets.Button(description="Multiply")
divide_button = widgets.Button(description="Divide")
output = widgets.Output()

# Define button click handlers
def on_add_button_clicked(b):
    with output:
        print(f"Result: {add_numbers(num1.value, num2.value)}")

def on_subtract_button_clicked(b):
    with output:
        print(f"Result: {subtract_numbers(num1.value, num2.value)}")

def on_multiply_button_clicked(b):
    with output:
        print(f"Result: {multiply_numbers(num1.value, num2.value)}")

def on_divide_button_clicked(b):
    with output:
        print(f"Result: {divide_numbers(num1.value, num2.value)}")

# Attach handlers to buttons
add_button.on_click(on_add_button_clicked)
subtract_button.on_click(on_subtract_button_clicked)
multiply_button.on_click(on_multiply_button_clicked)
divide_button.on_click(on_divide_button_clicked)

# Display widgets
display(num1, num2, add_button, subtract_button, multiply_button, divide_button, output)